[project]
name = "rogue"
version = "0.1.0"
description = "Add a short description here"
authors = ["da-verge <vterrel00@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-64"]

[tasks]

[dependencies]
pgzero = ">=1.2.1,<1.3"
